{
  "formatVersion": "1.1",
  "component": {
    "group": "ua.beengoo.logdo2",
    "module": "core",
    "version": "SNAPSHOT-20260212-093427",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-SNAPSHOT-20260212-093427.jar",
          "url": "core-SNAPSHOT-20260212-093427.jar",
          "size": 17600,
          "sha512": "fb8e54b6272e045aa9c2b823cf1fb7626ead7cb0c7e59b4fb6b0d6adaa0fead232e3ac7c2350e3920039d64b9b36bb1d9c9f448410f250d67aecaae6314f25df",
          "sha256": "ac586c3e7d873ca875e0e2c41388d07c56686f3a957dfa41ae9dad8e7c60f941",
          "sha1": "725010251da2f55153bac6999045583d636526b9",
          "md5": "f0f7411dc0265cb36c0624e622e51e1b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ua.beengoo.logdo2",
          "module": "logdo2-api",
          "version": {
            "requires": "SNAPSHOT-20260212-093427"
          }
        }
      ],
      "files": [
        {
          "name": "core-SNAPSHOT-20260212-093427.jar",
          "url": "core-SNAPSHOT-20260212-093427.jar",
          "size": 17600,
          "sha512": "fb8e54b6272e045aa9c2b823cf1fb7626ead7cb0c7e59b4fb6b0d6adaa0fead232e3ac7c2350e3920039d64b9b36bb1d9c9f448410f250d67aecaae6314f25df",
          "sha256": "ac586c3e7d873ca875e0e2c41388d07c56686f3a957dfa41ae9dad8e7c60f941",
          "sha1": "725010251da2f55153bac6999045583d636526b9",
          "md5": "f0f7411dc0265cb36c0624e622e51e1b"
        }
      ]
    }
  ]
}
