{
  "formatVersion": "1.1",
  "component": {
    "group": "ua.beengoo.logdo2",
    "module": "core",
    "version": "SNAPSHOT-20260212-090852",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-SNAPSHOT-20260212-090852.jar",
          "url": "core-SNAPSHOT-20260212-090852.jar",
          "size": 17600,
          "sha512": "77492b0d6777b4bf5e5560c4455c099dd4a1d8b95e32e239d5a15328f539de1acfcff7ec83df9347335d68f564b16bd00630b2ebebec7c4597fd11cd699e9b79",
          "sha256": "1dab18d6e0c14c628df96391c2b8fe851ec8b17afdefc04137f4463761d44d93",
          "sha1": "995dbc3fb9c1b536eeedbbb2238402cb82baef67",
          "md5": "25307e9a1f8325410d4c6793a45e4eee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ua.beengoo.logdo2",
          "module": "logdo2-api",
          "version": {
            "requires": "SNAPSHOT-20260212-090852"
          }
        }
      ],
      "files": [
        {
          "name": "core-SNAPSHOT-20260212-090852.jar",
          "url": "core-SNAPSHOT-20260212-090852.jar",
          "size": 17600,
          "sha512": "77492b0d6777b4bf5e5560c4455c099dd4a1d8b95e32e239d5a15328f539de1acfcff7ec83df9347335d68f564b16bd00630b2ebebec7c4597fd11cd699e9b79",
          "sha256": "1dab18d6e0c14c628df96391c2b8fe851ec8b17afdefc04137f4463761d44d93",
          "sha1": "995dbc3fb9c1b536eeedbbb2238402cb82baef67",
          "md5": "25307e9a1f8325410d4c6793a45e4eee"
        }
      ]
    }
  ]
}
