{
  "formatVersion": "1.1",
  "component": {
    "group": "ua.beengoo.logdo2",
    "module": "core",
    "version": "SNAPSHOT-20260212-100429",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-SNAPSHOT-20260212-100429.jar",
          "url": "core-SNAPSHOT-20260212-100429.jar",
          "size": 17600,
          "sha512": "d7e4123b06b44b6574e7655f3d727a9f0d84c1a595d70b83e2681924f4f6cc5188ad94babdc6acab05170d11fcc38d09cb1893c87ad3467e5a5cffc9ec053dc6",
          "sha256": "cc545fb17f96703dc24c2a097d4efd6144298be176c88d6a8ab6829710162341",
          "sha1": "55dac8d84ef99d57f61d930c66cc9baaee02edd2",
          "md5": "7844cd9f19df6817cf0d1c1ed6426c40"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ua.beengoo.logdo2",
          "module": "logdo2-api",
          "version": {
            "requires": "SNAPSHOT-20260212-100429"
          }
        }
      ],
      "files": [
        {
          "name": "core-SNAPSHOT-20260212-100429.jar",
          "url": "core-SNAPSHOT-20260212-100429.jar",
          "size": 17600,
          "sha512": "d7e4123b06b44b6574e7655f3d727a9f0d84c1a595d70b83e2681924f4f6cc5188ad94babdc6acab05170d11fcc38d09cb1893c87ad3467e5a5cffc9ec053dc6",
          "sha256": "cc545fb17f96703dc24c2a097d4efd6144298be176c88d6a8ab6829710162341",
          "sha1": "55dac8d84ef99d57f61d930c66cc9baaee02edd2",
          "md5": "7844cd9f19df6817cf0d1c1ed6426c40"
        }
      ]
    }
  ]
}
