{
  "formatVersion": "1.1",
  "component": {
    "group": "ua.beengoo.logdo2",
    "module": "core",
    "version": "SNAPSHOT-20260215-110923",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-SNAPSHOT-20260215-110923.jar",
          "url": "core-SNAPSHOT-20260215-110923.jar",
          "size": 17600,
          "sha512": "c80c957928cf519f7f7c7324cc91fec1b69df13c90c3bf1d1c4335a33f7143456f84b1f4cf5ec741ffb2ede6924f83151253f03db78c53ab5c39c6edf506105f",
          "sha256": "46697e3df1f3d7e87a1681ab5c46ae3a9a4144e8b9b4feea6c1704137e9df3db",
          "sha1": "12cafb8e22dde90f607212e2381aabc07fa32fd7",
          "md5": "019cfee71d49d926c17ee6366d7261d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ua.beengoo.logdo2",
          "module": "logdo2-api",
          "version": {
            "requires": "SNAPSHOT-20260215-110923"
          }
        }
      ],
      "files": [
        {
          "name": "core-SNAPSHOT-20260215-110923.jar",
          "url": "core-SNAPSHOT-20260215-110923.jar",
          "size": 17600,
          "sha512": "c80c957928cf519f7f7c7324cc91fec1b69df13c90c3bf1d1c4335a33f7143456f84b1f4cf5ec741ffb2ede6924f83151253f03db78c53ab5c39c6edf506105f",
          "sha256": "46697e3df1f3d7e87a1681ab5c46ae3a9a4144e8b9b4feea6c1704137e9df3db",
          "sha1": "12cafb8e22dde90f607212e2381aabc07fa32fd7",
          "md5": "019cfee71d49d926c17ee6366d7261d6"
        }
      ]
    }
  ]
}
